#!/bin/sh

set -e

if [ -z "$(ls -A /data)" ]; then
    exec s6-setuidgid app initdb -E UTF8 -U app

    cat >> /data/postgresql.conf << EOF
listen_addresses='*'
log_directory = '/var/log/app'
EOF

    cat > /data/pg_hba.conf << EOF
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5
host    all             all             172.16.0.0/12           md5
host    all             all             10.0.0.0/8              md5
EOF

    cat << EOF | exec s6-setuidgid app postgres --single postgres
CREATE DATABASE app ENCODING 'UTF8';
ALTER USER app WITH PASSWORD '$PGPASS';
EOF

    if [ -f /app.sql ]; then
        exec s6-setuidgid app pg_ctl -o "-c listen_addresses='localhost'" -w start
        exec s6-setuidgid app psql -f /app.sql app

        if [ -f /data.sql ]; then
            exec s6-setuidgid app psql -f /data.sql app
        fi

        exec s6-setuidgid app pg_ctl -m fast -w stop
    fi
else
    find /data -type d -exec chmod 700 {} \;
    find /data -type f -exec chmod 600 {} \;
fi

exec s6-setuidgid app postgres
