#!/bin/sh

set -euo pipefail

chown -R app:app /run/mysqld /var/log/app

if [ -z "$(ls -A /data)" ]; then
    mysql_install_db --user=app --datadir=/data --auth-root-authentication-method=normal
    mysqld --user=app --skip-networking &

    until mysqladmin -uroot ping > /dev/null 2>&1; do
        echo -n "."; sleep 0.2
    done

    mysql -uroot << EOF
        DROP DATABASE IF EXISTS test;
        CREATE DATABASE app DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
        DELETE FROM mysql.user;
        CREATE USER 'app'@'%' IDENTIFIED BY '$MYPASS';
        GRANT ALL PRIVILEGES ON *.* TO 'app'@'%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
EOF

    for file in `find /init/mysql -type f -name '*.sql' | sort`; do
        mysql -uapp -p"$MYPASS" app < $file
    done

    mysqladmin -uapp -p"$MYPASS" shutdown
else
    find /data -type d -exec chmod 700 {} \;
    find /data -type f -exec chmod 600 {} \;
fi

grep '\[mysqldump\]' /etc/my.cnf || cat >> /etc/my.cnf << EOF
[mysqldump]
user=app
password=$MYPASS
EOF
